# Generated by Django 4.2.6 on 2023-10-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('video_link', models.URLField(verbose_name='Ссылка на видео')),
                ('viewing_duration', models.IntegerField(verbose_name='Длительность просмотра')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='LessonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала просмотра')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания просмотра')),
                ('status', models.CharField(choices=[('viewed', 'Просмотрено'), ('not_viewed', 'Не просмотрено')], default='not_viewed', max_length=20, verbose_name='Статус просмотра')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
